// Extracts the pure engine functions from bank-of-dad-app.html into a
// standalone CommonJS module (engine.gen.js) so they can be unit- and
// mutation-tested in isolation. Kept in sync by re-running this script.
const fs = require('fs');
const path = require('path');

// Look for the app HTML relative to this script first (archive layout:
// tests/ sits beside bank-of-dad-app.html), then fall back to the dev path.
const CANDIDATES = [
  path.join(__dirname, '..', 'bank-of-dad-app.html'),
  path.join(__dirname, '..', 'public', 'app', 'index.html'),
  '/mnt/user-data/outputs/bank-of-dad-app.html',
];
const SRC = CANDIDATES.find(p => fs.existsSync(p));
if (!SRC) { console.error('Could not find bank-of-dad-app.html in', CANDIDATES); process.exit(1); }
const html = fs.readFileSync(SRC, 'utf8');
const script = html.match(/<script>([\s\S]*)<\/script>/)[1];

// The pure functions/consts we want, in dependency order. We slice each one
// out of the source by matching its declaration and balancing braces.
const WANTED = [
  { type: 'const', name: 'CHALLENGE_TEMPLATES' },
  { type: 'const', name: 'DIFFICULTY_MULTIPLIERS' },
  { type: 'func', name: 'ageGroupFor' },
  { type: 'func', name: 'weeklyAllowanceFor' },
  { type: 'func', name: 'buildChallengePrompt' },
  { type: 'func', name: 'parseChallengeCsv' },
  { type: 'func', name: 'buildThemePrompt' },
  { type: 'func', name: 'parseThemeColors' },
  { type: 'func', name: 'bestTextOn' },
  { type: 'func', name: 'tintToward' },
  { type: 'func', name: 'completedYears' },
  { type: 'func', name: 'tierFor' },
  { type: 'const', name: 'BADGES' },
  { type: 'const', name: 'SELF_BADGE_IDS' },
  { type: 'func', name: 'badgeMilestones' },
  { type: 'func', name: 'earnedBadgeIds' },
  { type: 'func', name: 'badgeLabel' },
  { type: 'func', name: 'difficultyMultiplier' },
  { type: 'func', name: 'parseBonusPct' },
  { type: 'func', name: 'parseMilestones' },
  { type: 'func', name: 'payCadenceConfig' },
  { type: 'func', name: 'weeklyRateFor' },
  { type: 'func', name: 'weeklyInterestFor' },
  { type: 'func', name: 'hasCrossed' },
  { type: 'func', name: 'accrueInterest' },
  { type: 'func', name: 'interestOver' },
  { type: 'func', name: 'owedInterest' },
  { type: 'func', name: 'topUpBreakdown' },
  { type: 'func', name: 'getChildBase' },
  { type: 'func', name: 'dueWeeks' },
  { type: 'func', name: 'buildLedger' },
  { type: 'func', name: 'canSpend' },
  { type: 'func', name: 'convertAmounts' },
  { type: 'func', name: 'rupeesExact' },
  { type: 'func', name: 'rupees' },
  { type: 'func', name: 'getTodaysEarned' },
  { type: 'func', name: 'serializeState' },
  { type: 'const', name: 'DEFAULT_BADGE_MILESTONES' },
  { type: 'const', name: 'DEFAULT_SETTINGS' },
  { type: 'func', name: 'warn' },
  { type: 'func', name: 'esc' },
  { type: 'func', name: 'cleanStr' },
  { type: 'func', name: 'cleanSym' },
  { type: 'func', name: 'cleanNum' },
  { type: 'func', name: 'safeIdStr' },
  { type: 'func', name: 'sanitizeState' },
  { type: 'func', name: 'parseBackup' },
  { type: 'func', name: 'hasPendingAllowance' },
  { type: 'func', name: 'projectForward' },
  { type: 'func', name: 'weeksToGoal' },
];

function sliceBalanced(src, startIdx) {
  // Find first '{' at/after startIdx, then balance braces.
  let i = src.indexOf('{', startIdx);
  let depth = 0;
  for (; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') {
      depth--;
      if (depth === 0) {
        // for const {...} we also need the trailing ';'
        let end = i + 1;
        if (src[end] === ';') end++;
        return end;
      }
    }
  }
  throw new Error('unbalanced');
}

let out = '// AUTO-GENERATED by extract-engine.js — do not edit by hand.\n';
out += '// Mutable state so functions that read settings can be driven by tests.\n';
out += "const MS_DAY = 24 * 3600 * 1000;\n";
out += "let state = { settings: { currency: '₹', base: 100, rate: 10, frequency: 'daily' } };\n";
out += 'function __setState(s){ state = s; }\n\n';

for (const w of WANTED) {
  let re;
  if (w.type === 'func') re = new RegExp('function\\s+' + w.name + '\\s*\\(');
  else re = new RegExp('const\\s+' + w.name + '\\s*=');
  const m = script.match(re);
  if (!m) { console.error('NOT FOUND:', w.name); process.exit(1); }
  const start = m.index;
  let end;
  if (w.type === 'const') {
    // Peek at what follows '=' : an object '{...}' balances braces; anything
    // else (array, literal) ends at the first ';' at depth 0.
    const eq = script.indexOf('=', start);
    const after = script.slice(eq + 1).replace(/^\s+/, '')[0];
    if (after === '{') {
      end = sliceBalanced(script, start);
    } else {
      end = script.indexOf(';', start) + 1;
    }
  } else {
    end = sliceBalanced(script, start);
  }
  out += script.slice(start, end).trim() + '\n\n';
}

// Export everything
out += 'module.exports = { __setState, get state(){return state;}, MS_DAY,\n';
out += '  ' + WANTED.map(w => w.name).join(', ') + '\n};\n';

fs.writeFileSync(path.join(__dirname, 'engine.gen.js'), out);
console.log('Wrote engine.gen.js (' + out.length + ' bytes, ' + WANTED.length + ' symbols)');
